packageExtensions:
  istanbul-lib-processinfo@*:
    dependencies:
      mkdirp: ^1.0.4
  tcompare@*:
    dependencies:
      diff: ^5.0.0
  treport@*:
    dependencies:
      tap-yaml: ^1.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-bump.cjs
    spec: "https://github.com/cometkim/yarn-plugin-bump/releases/download/v0.0.7/plugin-bump.js"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-2.4.0.cjs
