changesetBaseRefs:
- "main"
- "origin/main"
- "upstream/main"

packageExtensions:
  istanbul-lib-processinfo@*:
    dependencies:
      mkdirp: ^1.0.4
  jest-config@>=26.0.0:
    dependencies:
      ts-node: "*"
  tcompare@*:
    dependencies:
      diff: ^5.0.0
  treport@*:
    dependencies:
      tap-yaml: ^1.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
