module.exports = {
  inputSourceMap: true,
  sourceMaps: true,

  // Additional comments can be found in source map and type definitions.
  comments: false,

  presets: [
    '@babel/preset-typescript',
    ['@babel/preset-env', {
      useBuiltIns: 'usage',
      corejs: 3,
      shippedProposals: true,
    }],
  ],

  env: {
    node: {
      presets: [
        ['@babel/preset-env', {
          modules: 'commonjs',
          targets: {
            node: 10,
          },
        }],
      ],
      plugins: [
        ['@babel/plugin-transform-runtime', {
          corejs: {
            version: 3,
            proposals: true,
          },
        }],
      ],
    },

    module: {
      presets: [
        ['@babel/preset-env', {
          modules: false,
          bugfixes: true,
          targets: {
            esmodules: true,
          },
        }],
      ],
      plugins: [
        ['@babel/plugin-transform-runtime', {
          corejs: {
            version: 3,
            proposals: true,
          },
          useEsModules: true,
        }],
      ],
    },

    // UMD bundle will be generated by Rollup.
    browser: {
      presets: [
        ['@babel/preset-env', {
          targets: {
            browsers: '> 0.25%, ie >= 11, not dead',
          },
        }],
      ],
    },
  },
};
