name: Integration

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  chore:
    name: Testing chores
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 15.x

      - name: Check that the Yarn files don''t change on new installs
        shell: bash
        run: |
          yarn --immutable --immutable-cache

      - name: Check that the cache files are consistent with their remote sources
        shell: bash
        run: |
          if [[ $(git diff --name-only "$(git merge-base origin/"$TARGET_BRANCH" HEAD)" HEAD -- .yarn/cache | wc -l) -gt 0 ]]; then
            yarn --immutable --immutable-cache --check-cache
          fi
        if: |
          github.event.pull_request != ''

      - name: Check that the PR describes which packages should be bumped
        shell: bash
        run: |
          yarn version check
        if: |
          github.event.pull_request != ''

      - name: Check for linting errors
        run: yarn lint packages

      - name: Check for type errors
        run: yarn tsc

  test:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 15.x

      - name: Test all packages
        run: yarn workspaces foreach -p run test

      - name: Generate coverage reports
        run: yarn workspaces foreach -p run test --coverage-report=json

      - name: Send reports to CodeCov
        uses: codecov/codecov-action@v1
        with:
          flags: core,graphql-utils
