name: Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  chore:
    name: Check chores
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Check that the Yarn files don''t change on new installs
        shell: bash
        run: |
          yarn --immutable --immutable-cache

      - name: Check that the cache files are consistent with their remote sources
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        run: |
          if [[ $(git diff --name-only "$(git merge-base origin/"$TARGET_BRANCH" HEAD)" HEAD -- .yarn/cache | wc -l) -gt 0 ]]; then
            yarn --immutable --immutable-cache --check-cache
          fi
        env:
          TARGET_BRANCH: ${{github.event.pull_request.base.ref}}

      - name: Build package dependencies
        run: |
          yarn workspaces foreach --topological-dev --parallel run build

      - name: Check for linting errors
        run: yarn lint

      - name: Check for type errors
        run: yarn type-check

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Test all packages
        run: |
          yarn test --coverage

      - name: Send coverage reports to CodeCov
        uses: codecov/codecov-action@v2
        with:
          flags: core,react-utils,graphql-utils,urql-utils
